# nodejs role ansible-galaxy
# https://github.com/geerlingguy/ansible-role-nodejs
- name: geerlingguy.nodejs

# golang role ansible-galaxy
# https://github.com/fubarhouse/ansible-role-golang
- name: fubarhouse.golang

